In [6]:
##Author: panthadeep_b; Time: 19.33 IST - 22Feb'25
##WAP to implement Support Vector Machine (SVM) classifier

import sys
import pandas as pd
import numpy as np
from array import *
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc 
import seaborn as sns

data_set = pd.read_csv("Iris.csv");
##print(data_set);

x = data_set.iloc[:,[0,1,2,3]];
y = data_set.iloc[:,5];

print("X:\n",x);
print("Y:\n",y);

# Splitting the dataset into training and test set
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0); 
 
scale = StandardScaler()    
x_train = scale.fit_transform(x_train)    
x_test = scale.transform(x_test)  

#print("X_train:\n",x_train);
#print("Y_test:\n",y_test);

model = SVC(kernel='linear', random_state=0)
model.fit(x_train, y_train)  


#***Predicting the test set result****  
y_pred = model.predict(x_test) 

#Creating the Confusion matrix  
cm = confusion_matrix(y_test, y_pred)  
print(cm);

# evaluate the model
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


X:
      sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]
Y:
 0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: class-encode, Length: 150, dtype: int64
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
Confusion Matrix:
 [[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]

Classification Report:
          